/* tslint:disable */
/* eslint-disable */
/**
 * Solutions API
 * REST API for technical solutions organized by categories and subcategories
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Category
 */
export interface Category {
    /**
     * 
     * @type {any}
     * @memberof Category
     */
    'id'?: any;
    /**
     * 
     * @type {any}
     * @memberof Category
     */
    'name'?: any;
    /**
     * 
     * @type {any}
     * @memberof Category
     */
    'slug'?: any;
}
/**
 * 
 * @export
 * @interface LoginInput
 */
export interface LoginInput {
    /**
     * 
     * @type {any}
     * @memberof LoginInput
     */
    'email': any;
    /**
     * 
     * @type {any}
     * @memberof LoginInput
     */
    'password': any;
}
/**
 * 
 * @export
 * @interface MarkSolutionHelpful200Response
 */
export interface MarkSolutionHelpful200Response {
    /**
     * 
     * @type {any}
     * @memberof MarkSolutionHelpful200Response
     */
    'id'?: any;
    /**
     * 
     * @type {any}
     * @memberof MarkSolutionHelpful200Response
     */
    'helpful_count'?: any;
}
/**
 * 
 * @export
 * @interface PaginatedSolutions
 */
export interface PaginatedSolutions {
    /**
     * 
     * @type {any}
     * @memberof PaginatedSolutions
     */
    'page'?: any;
    /**
     * 
     * @type {any}
     * @memberof PaginatedSolutions
     */
    'limit'?: any;
    /**
     * 
     * @type {any}
     * @memberof PaginatedSolutions
     */
    'total'?: any;
    /**
     * 
     * @type {any}
     * @memberof PaginatedSolutions
     */
    'data'?: any;
}
/**
 * 
 * @export
 * @interface RegisterInput
 */
export interface RegisterInput {
    /**
     * 
     * @type {any}
     * @memberof RegisterInput
     */
    'username': any;
    /**
     * 
     * @type {any}
     * @memberof RegisterInput
     */
    'email': any;
    /**
     * 
     * @type {any}
     * @memberof RegisterInput
     */
    'password': any;
}
/**
 * 
 * @export
 * @interface Solution
 */
export interface Solution {
    /**
     * 
     * @type {any}
     * @memberof Solution
     */
    'id'?: any;
    /**
     * 
     * @type {any}
     * @memberof Solution
     */
    'title'?: any;
    /**
     * 
     * @type {any}
     * @memberof Solution
     */
    'content'?: any;
    /**
     * 
     * @type {any}
     * @memberof Solution
     */
    'difficulty'?: SolutionDifficultyEnum;
    /**
     * 
     * @type {any}
     * @memberof Solution
     */
    'helpful_count'?: any;
    /**
     * 
     * @type {any}
     * @memberof Solution
     */
    'subcategory_id'?: any;
    /**
     * 
     * @type {any}
     * @memberof Solution
     */
    'created_at'?: any;
}

export const SolutionDifficultyEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;

export type SolutionDifficultyEnum = typeof SolutionDifficultyEnum[keyof typeof SolutionDifficultyEnum];

/**
 * 
 * @export
 * @interface SolutionInput
 */
export interface SolutionInput {
    /**
     * 
     * @type {any}
     * @memberof SolutionInput
     */
    'title': any;
    /**
     * 
     * @type {any}
     * @memberof SolutionInput
     */
    'content': any;
    /**
     * 
     * @type {any}
     * @memberof SolutionInput
     */
    'subcategory_id': any;
    /**
     * 
     * @type {any}
     * @memberof SolutionInput
     */
    'difficulty'?: SolutionInputDifficultyEnum;
}

export const SolutionInputDifficultyEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;

export type SolutionInputDifficultyEnum = typeof SolutionInputDifficultyEnum[keyof typeof SolutionInputDifficultyEnum];

/**
 * 
 * @export
 * @interface Subcategory
 */
export interface Subcategory {
    /**
     * 
     * @type {any}
     * @memberof Subcategory
     */
    'id'?: any;
    /**
     * 
     * @type {any}
     * @memberof Subcategory
     */
    'name'?: any;
    /**
     * 
     * @type {any}
     * @memberof Subcategory
     */
    'slug'?: any;
    /**
     * 
     * @type {any}
     * @memberof Subcategory
     */
    'category_id'?: any;
}
/**
 * 
 * @export
 * @interface UserPublic
 */
export interface UserPublic {
    /**
     * 
     * @type {any}
     * @memberof UserPublic
     */
    'id'?: any;
    /**
     * 
     * @type {any}
     * @memberof UserPublic
     */
    'username'?: any;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Login
         * @param {LoginInput} loginInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser: async (loginInput: LoginInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginInput' is not null or undefined
            assertParamExists('loginUser', 'loginInput', loginInput)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register
         * @param {RegisterInput} registerInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser: async (registerInput: RegisterInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerInput' is not null or undefined
            assertParamExists('registerUser', 'registerInput', registerInput)
            const localVarPath = `/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Login
         * @param {LoginInput} loginInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginUser(loginInput: LoginInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginUser(loginInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Register
         * @param {RegisterInput} registerInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerUser(registerInput: RegisterInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserPublic>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerUser(registerInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary Login
         * @param {LoginInput} loginInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser(loginInput: LoginInput, options?: any): AxiosPromise<void> {
            return localVarFp.loginUser(loginInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register
         * @param {RegisterInput} registerInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser(registerInput: RegisterInput, options?: any): AxiosPromise<UserPublic> {
            return localVarFp.registerUser(registerInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary Login
     * @param {LoginInput} loginInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public loginUser(loginInput: LoginInput, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).loginUser(loginInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register
     * @param {RegisterInput} registerInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public registerUser(registerInput: RegisterInput, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).registerUser(registerInput, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CategoriesApi - axios parameter creator
 * @export
 */
export const CategoriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategories: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get category
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategoryBySlug: async (slug: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('getCategoryBySlug', 'slug', slug)
            const localVarPath = `/categories/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Solutions under category
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutionsByCategory: async (slug: any, page?: any, limit?: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('getSolutionsByCategory', 'slug', slug)
            const localVarPath = `/categories/{slug}/solutions`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List subcategories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubcategories: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/subcategories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get subcategory
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubcategoryBySlug: async (slug: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('getSubcategoryBySlug', 'slug', slug)
            const localVarPath = `/subcategories/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CategoriesApi - functional programming interface
 * @export
 */
export const CategoriesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CategoriesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCategories(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCategories(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get category
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCategoryBySlug(slug: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Category>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCategoryBySlug(slug, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Solutions under category
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSolutionsByCategory(slug: any, page?: any, limit?: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedSolutions>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSolutionsByCategory(slug, page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List subcategories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubcategories(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubcategories(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get subcategory
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubcategoryBySlug(slug: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subcategory>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubcategoryBySlug(slug, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CategoriesApi - factory interface
 * @export
 */
export const CategoriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CategoriesApiFp(configuration)
    return {
        /**
         * 
         * @summary List categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategories(options?: any): AxiosPromise<any> {
            return localVarFp.getCategories(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get category
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategoryBySlug(slug: any, options?: any): AxiosPromise<Category> {
            return localVarFp.getCategoryBySlug(slug, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Solutions under category
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutionsByCategory(slug: any, page?: any, limit?: any, options?: any): AxiosPromise<PaginatedSolutions> {
            return localVarFp.getSolutionsByCategory(slug, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List subcategories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubcategories(options?: any): AxiosPromise<any> {
            return localVarFp.getSubcategories(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get subcategory
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubcategoryBySlug(slug: any, options?: any): AxiosPromise<Subcategory> {
            return localVarFp.getSubcategoryBySlug(slug, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CategoriesApi - object-oriented interface
 * @export
 * @class CategoriesApi
 * @extends {BaseAPI}
 */
export class CategoriesApi extends BaseAPI {
    /**
     * 
     * @summary List categories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public getCategories(options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getCategories(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get category
     * @param {any} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public getCategoryBySlug(slug: any, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getCategoryBySlug(slug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Solutions under category
     * @param {any} slug 
     * @param {any} [page] 
     * @param {any} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public getSolutionsByCategory(slug: any, page?: any, limit?: any, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getSolutionsByCategory(slug, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List subcategories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public getSubcategories(options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getSubcategories(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get subcategory
     * @param {any} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public getSubcategoryBySlug(slug: any, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getSubcategoryBySlug(slug, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DeveloperApi - axios parameter creator
 * @export
 */
export const DeveloperApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get API key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApiKey: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/me/api-key`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Regenerate API key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regenerateApiKey: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/me/api-key/regenerate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DeveloperApi - functional programming interface
 * @export
 */
export const DeveloperApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DeveloperApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get API key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getApiKey(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getApiKey(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Regenerate API key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async regenerateApiKey(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.regenerateApiKey(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DeveloperApi - factory interface
 * @export
 */
export const DeveloperApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DeveloperApiFp(configuration)
    return {
        /**
         * 
         * @summary Get API key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApiKey(options?: any): AxiosPromise<void> {
            return localVarFp.getApiKey(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Regenerate API key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regenerateApiKey(options?: any): AxiosPromise<void> {
            return localVarFp.regenerateApiKey(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DeveloperApi - object-oriented interface
 * @export
 * @class DeveloperApi
 * @extends {BaseAPI}
 */
export class DeveloperApi extends BaseAPI {
    /**
     * 
     * @summary Get API key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeveloperApi
     */
    public getApiKey(options?: AxiosRequestConfig) {
        return DeveloperApiFp(this.configuration).getApiKey(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Regenerate API key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeveloperApi
     */
    public regenerateApiKey(options?: AxiosRequestConfig) {
        return DeveloperApiFp(this.configuration).regenerateApiKey(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SolutionsApi - axios parameter creator
 * @export
 */
export const SolutionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create solution
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSolution: async (solutionInput: SolutionInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'solutionInput' is not null or undefined
            assertParamExists('createSolution', 'solutionInput', solutionInput)
            const localVarPath = `/solutions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(solutionInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSolution: async (id: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteSolution', 'id', id)
            const localVarPath = `/solutions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutionById: async (id: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSolutionById', 'id', id)
            const localVarPath = `/solutions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search across title and content, optionally filter by subcategory
         * @summary List solutions
         * @param {any} [search] 
         * @param {any} [subcategory] Subcategory ID filter
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutions: async (search?: any, subcategory?: any, page?: any, limit?: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/solutions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (subcategory !== undefined) {
                localVarQueryParameter['subcategory'] = subcategory;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Solutions under subcategory
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutionsBySubcategory: async (slug: any, page?: any, limit?: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('getSolutionsBySubcategory', 'slug', slug)
            const localVarPath = `/subcategories/{slug}/solutions`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Mark solution helpful
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markSolutionHelpful: async (id: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('markSolutionHelpful', 'id', id)
            const localVarPath = `/solutions/{id}/helpful`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update solution
         * @param {any} id 
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSolution: async (id: any, solutionInput: SolutionInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateSolution', 'id', id)
            // verify required parameter 'solutionInput' is not null or undefined
            assertParamExists('updateSolution', 'solutionInput', solutionInput)
            const localVarPath = `/solutions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(solutionInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SolutionsApi - functional programming interface
 * @export
 */
export const SolutionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SolutionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create solution
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSolution(solutionInput: SolutionInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Solution>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSolution(solutionInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSolution(id: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSolution(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSolutionById(id: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Solution>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSolutionById(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Search across title and content, optionally filter by subcategory
         * @summary List solutions
         * @param {any} [search] 
         * @param {any} [subcategory] Subcategory ID filter
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSolutions(search?: any, subcategory?: any, page?: any, limit?: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedSolutions>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSolutions(search, subcategory, page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Solutions under subcategory
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSolutionsBySubcategory(slug: any, page?: any, limit?: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedSolutions>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSolutionsBySubcategory(slug, page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Mark solution helpful
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markSolutionHelpful(id: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MarkSolutionHelpful200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.markSolutionHelpful(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update solution
         * @param {any} id 
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSolution(id: any, solutionInput: SolutionInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Solution>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSolution(id, solutionInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SolutionsApi - factory interface
 * @export
 */
export const SolutionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SolutionsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create solution
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSolution(solutionInput: SolutionInput, options?: any): AxiosPromise<Solution> {
            return localVarFp.createSolution(solutionInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSolution(id: any, options?: any): AxiosPromise<void> {
            return localVarFp.deleteSolution(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutionById(id: any, options?: any): AxiosPromise<Solution> {
            return localVarFp.getSolutionById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Search across title and content, optionally filter by subcategory
         * @summary List solutions
         * @param {any} [search] 
         * @param {any} [subcategory] Subcategory ID filter
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutions(search?: any, subcategory?: any, page?: any, limit?: any, options?: any): AxiosPromise<PaginatedSolutions> {
            return localVarFp.getSolutions(search, subcategory, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Solutions under subcategory
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutionsBySubcategory(slug: any, page?: any, limit?: any, options?: any): AxiosPromise<PaginatedSolutions> {
            return localVarFp.getSolutionsBySubcategory(slug, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Mark solution helpful
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markSolutionHelpful(id: any, options?: any): AxiosPromise<MarkSolutionHelpful200Response> {
            return localVarFp.markSolutionHelpful(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update solution
         * @param {any} id 
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSolution(id: any, solutionInput: SolutionInput, options?: any): AxiosPromise<Solution> {
            return localVarFp.updateSolution(id, solutionInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SolutionsApi - object-oriented interface
 * @export
 * @class SolutionsApi
 * @extends {BaseAPI}
 */
export class SolutionsApi extends BaseAPI {
    /**
     * 
     * @summary Create solution
     * @param {SolutionInput} solutionInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public createSolution(solutionInput: SolutionInput, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).createSolution(solutionInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete solution
     * @param {any} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public deleteSolution(id: any, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).deleteSolution(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get solution
     * @param {any} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public getSolutionById(id: any, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).getSolutionById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Search across title and content, optionally filter by subcategory
     * @summary List solutions
     * @param {any} [search] 
     * @param {any} [subcategory] Subcategory ID filter
     * @param {any} [page] 
     * @param {any} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public getSolutions(search?: any, subcategory?: any, page?: any, limit?: any, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).getSolutions(search, subcategory, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Solutions under subcategory
     * @param {any} slug 
     * @param {any} [page] 
     * @param {any} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public getSolutionsBySubcategory(slug: any, page?: any, limit?: any, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).getSolutionsBySubcategory(slug, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Mark solution helpful
     * @param {any} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public markSolutionHelpful(id: any, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).markSolutionHelpful(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update solution
     * @param {any} id 
     * @param {SolutionInput} solutionInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public updateSolution(id: any, solutionInput: SolutionInput, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).updateSolution(id, solutionInput, options).then((request) => request(this.axios, this.basePath));
    }
}



