/**
 * Solutions API
 * REST API for technical solutions organized by categories and subcategories
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Solution {
    'id'?: any | null;
    'title'?: any | null;
    'content'?: any | null;
    'difficulty'?: Solution.DifficultyEnum;
    'helpful_count'?: any | null;
    'subcategory_id'?: any | null;
    'created_at'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "any"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "any"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "any"
        },
        {
            "name": "difficulty",
            "baseName": "difficulty",
            "type": "Solution.DifficultyEnum"
        },
        {
            "name": "helpful_count",
            "baseName": "helpful_count",
            "type": "any"
        },
        {
            "name": "subcategory_id",
            "baseName": "subcategory_id",
            "type": "any"
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return Solution.attributeTypeMap;
    }
}

export namespace Solution {
    export enum DifficultyEnum {
        Beginner = <any> 'beginner',
        Intermediate = <any> 'intermediate',
        Advanced = <any> 'advanced'
    }
}
