/* tslint:disable */
/* eslint-disable */
/**
 * Solutions API
 * REST API for technical solutions organized by categories and subcategories
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Category } from '../models';
// @ts-ignore
import { PaginatedSolutions } from '../models';
// @ts-ignore
import { Subcategory } from '../models';
/**
 * CategoriesApi - axios parameter creator
 * @export
 */
export const CategoriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategories: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get category
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategoryBySlug: async (slug: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('getCategoryBySlug', 'slug', slug)
            const localVarPath = `/categories/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Solutions under category
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutionsByCategory: async (slug: any, page?: any, limit?: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('getSolutionsByCategory', 'slug', slug)
            const localVarPath = `/categories/{slug}/solutions`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List subcategories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubcategories: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/subcategories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get subcategory
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubcategoryBySlug: async (slug: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('getSubcategoryBySlug', 'slug', slug)
            const localVarPath = `/subcategories/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CategoriesApi - functional programming interface
 * @export
 */
export const CategoriesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CategoriesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCategories(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCategories(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get category
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCategoryBySlug(slug: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Category>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCategoryBySlug(slug, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Solutions under category
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSolutionsByCategory(slug: any, page?: any, limit?: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedSolutions>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSolutionsByCategory(slug, page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List subcategories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubcategories(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubcategories(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get subcategory
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubcategoryBySlug(slug: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subcategory>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubcategoryBySlug(slug, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CategoriesApi - factory interface
 * @export
 */
export const CategoriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CategoriesApiFp(configuration)
    return {
        /**
         * 
         * @summary List categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategories(options?: AxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getCategories(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get category
         * @param {CategoriesApiGetCategoryBySlugRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategoryBySlug(requestParameters: CategoriesApiGetCategoryBySlugRequest, options?: AxiosRequestConfig): AxiosPromise<Category> {
            return localVarFp.getCategoryBySlug(requestParameters.slug, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Solutions under category
         * @param {CategoriesApiGetSolutionsByCategoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutionsByCategory(requestParameters: CategoriesApiGetSolutionsByCategoryRequest, options?: AxiosRequestConfig): AxiosPromise<PaginatedSolutions> {
            return localVarFp.getSolutionsByCategory(requestParameters.slug, requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List subcategories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubcategories(options?: AxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getSubcategories(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get subcategory
         * @param {CategoriesApiGetSubcategoryBySlugRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubcategoryBySlug(requestParameters: CategoriesApiGetSubcategoryBySlugRequest, options?: AxiosRequestConfig): AxiosPromise<Subcategory> {
            return localVarFp.getSubcategoryBySlug(requestParameters.slug, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getCategoryBySlug operation in CategoriesApi.
 * @export
 * @interface CategoriesApiGetCategoryBySlugRequest
 */
export interface CategoriesApiGetCategoryBySlugRequest {
    /**
     * 
     * @type {any}
     * @memberof CategoriesApiGetCategoryBySlug
     */
    readonly slug: any
}

/**
 * Request parameters for getSolutionsByCategory operation in CategoriesApi.
 * @export
 * @interface CategoriesApiGetSolutionsByCategoryRequest
 */
export interface CategoriesApiGetSolutionsByCategoryRequest {
    /**
     * 
     * @type {any}
     * @memberof CategoriesApiGetSolutionsByCategory
     */
    readonly slug: any

    /**
     * 
     * @type {any}
     * @memberof CategoriesApiGetSolutionsByCategory
     */
    readonly page?: any

    /**
     * 
     * @type {any}
     * @memberof CategoriesApiGetSolutionsByCategory
     */
    readonly limit?: any
}

/**
 * Request parameters for getSubcategoryBySlug operation in CategoriesApi.
 * @export
 * @interface CategoriesApiGetSubcategoryBySlugRequest
 */
export interface CategoriesApiGetSubcategoryBySlugRequest {
    /**
     * 
     * @type {any}
     * @memberof CategoriesApiGetSubcategoryBySlug
     */
    readonly slug: any
}

/**
 * CategoriesApi - object-oriented interface
 * @export
 * @class CategoriesApi
 * @extends {BaseAPI}
 */
export class CategoriesApi extends BaseAPI {
    /**
     * 
     * @summary List categories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public getCategories(options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getCategories(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get category
     * @param {CategoriesApiGetCategoryBySlugRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public getCategoryBySlug(requestParameters: CategoriesApiGetCategoryBySlugRequest, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getCategoryBySlug(requestParameters.slug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Solutions under category
     * @param {CategoriesApiGetSolutionsByCategoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public getSolutionsByCategory(requestParameters: CategoriesApiGetSolutionsByCategoryRequest, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getSolutionsByCategory(requestParameters.slug, requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List subcategories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public getSubcategories(options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getSubcategories(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get subcategory
     * @param {CategoriesApiGetSubcategoryBySlugRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public getSubcategoryBySlug(requestParameters: CategoriesApiGetSubcategoryBySlugRequest, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getSubcategoryBySlug(requestParameters.slug, options).then((request) => request(this.axios, this.basePath));
    }
}

