/**
 * Solutions API
 * REST API for technical solutions organized by categories and subcategories
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PaginatedSolutions {
    'page'?: any | null;
    'limit'?: any | null;
    'total'?: any | null;
    'data'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "page",
            "baseName": "page",
            "type": "any"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "any"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "any"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return PaginatedSolutions.attributeTypeMap;
    }
}

