/**
 * Solutions API
 * REST API for technical solutions organized by categories and subcategories
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SolutionInput {
    'title': any | null;
    'content': any | null;
    'subcategoryId': any | null;
    'difficulty'?: SolutionInput.DifficultyEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "any"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "any"
        },
        {
            "name": "subcategoryId",
            "baseName": "subcategory_id",
            "type": "any"
        },
        {
            "name": "difficulty",
            "baseName": "difficulty",
            "type": "SolutionInput.DifficultyEnum"
        }    ];

    static getAttributeTypeMap() {
        return SolutionInput.attributeTypeMap;
    }
}

export namespace SolutionInput {
    export enum DifficultyEnum {
        Beginner = <any> 'beginner',
        Intermediate = <any> 'intermediate',
        Advanced = <any> 'advanced'
    }
}
