/* tslint:disable */
/* eslint-disable */
/**
 * Solutions API
 * REST API for technical solutions organized by categories and subcategories
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * Human-readable error message
     * @type {any}
     * @memberof ErrorResponse
     */
    'error': any;
    /**
     * Machine-readable error code
     * @type {any}
     * @memberof ErrorResponse
     */
    'code'?: any;
}

