/* tslint:disable */
/* eslint-disable */
/**
 * Solutions API
 * REST API for technical solutions organized by categories and subcategories
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SolutionInput
 */
export interface SolutionInput {
    /**
     * 
     * @type {any}
     * @memberof SolutionInput
     */
    'title': any;
    /**
     * 
     * @type {any}
     * @memberof SolutionInput
     */
    'content': any;
    /**
     * 
     * @type {any}
     * @memberof SolutionInput
     */
    'subcategory_id': any;
    /**
     * 
     * @type {any}
     * @memberof SolutionInput
     */
    'difficulty'?: SolutionInputDifficultyEnum;
}

export const SolutionInputDifficultyEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;

export type SolutionInputDifficultyEnum = typeof SolutionInputDifficultyEnum[keyof typeof SolutionInputDifficultyEnum];


