/* tslint:disable */
/* eslint-disable */
/**
 * Solutions API
 * REST API for technical solutions organized by categories and subcategories
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Category } from '../models';
// @ts-ignore
import { PaginatedSolutions } from '../models';
// @ts-ignore
import { Subcategory } from '../models';
/**
 * CategoriesApi - axios parameter creator
 * @export
 */
export const CategoriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get category
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesSlugGet: async (slug: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('categoriesSlugGet', 'slug', slug)
            const localVarPath = `/categories/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Solutions under category
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesSlugSolutionsGet: async (slug: any, page?: any, limit?: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('categoriesSlugSolutionsGet', 'slug', slug)
            const localVarPath = `/categories/{slug}/solutions`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List subcategories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subcategoriesGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/subcategories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get subcategory
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subcategoriesSlugGet: async (slug: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('subcategoriesSlugGet', 'slug', slug)
            const localVarPath = `/subcategories/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CategoriesApi - functional programming interface
 * @export
 */
export const CategoriesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CategoriesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoriesGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get category
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoriesSlugGet(slug: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Category>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesSlugGet(slug, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Solutions under category
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoriesSlugSolutionsGet(slug: any, page?: any, limit?: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedSolutions>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesSlugSolutionsGet(slug, page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List subcategories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async subcategoriesGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subcategoriesGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get subcategory
         * @param {any} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async subcategoriesSlugGet(slug: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subcategory>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subcategoriesSlugGet(slug, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CategoriesApi - factory interface
 * @export
 */
export const CategoriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CategoriesApiFp(configuration)
    return {
        /**
         * 
         * @summary List categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesGet(options?: AxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.categoriesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get category
         * @param {CategoriesApiCategoriesSlugGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesSlugGet(requestParameters: CategoriesApiCategoriesSlugGetRequest, options?: AxiosRequestConfig): AxiosPromise<Category> {
            return localVarFp.categoriesSlugGet(requestParameters.slug, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Solutions under category
         * @param {CategoriesApiCategoriesSlugSolutionsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesSlugSolutionsGet(requestParameters: CategoriesApiCategoriesSlugSolutionsGetRequest, options?: AxiosRequestConfig): AxiosPromise<PaginatedSolutions> {
            return localVarFp.categoriesSlugSolutionsGet(requestParameters.slug, requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List subcategories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subcategoriesGet(options?: AxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.subcategoriesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get subcategory
         * @param {CategoriesApiSubcategoriesSlugGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subcategoriesSlugGet(requestParameters: CategoriesApiSubcategoriesSlugGetRequest, options?: AxiosRequestConfig): AxiosPromise<Subcategory> {
            return localVarFp.subcategoriesSlugGet(requestParameters.slug, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for categoriesSlugGet operation in CategoriesApi.
 * @export
 * @interface CategoriesApiCategoriesSlugGetRequest
 */
export interface CategoriesApiCategoriesSlugGetRequest {
    /**
     * 
     * @type {any}
     * @memberof CategoriesApiCategoriesSlugGet
     */
    readonly slug: any
}

/**
 * Request parameters for categoriesSlugSolutionsGet operation in CategoriesApi.
 * @export
 * @interface CategoriesApiCategoriesSlugSolutionsGetRequest
 */
export interface CategoriesApiCategoriesSlugSolutionsGetRequest {
    /**
     * 
     * @type {any}
     * @memberof CategoriesApiCategoriesSlugSolutionsGet
     */
    readonly slug: any

    /**
     * 
     * @type {any}
     * @memberof CategoriesApiCategoriesSlugSolutionsGet
     */
    readonly page?: any

    /**
     * 
     * @type {any}
     * @memberof CategoriesApiCategoriesSlugSolutionsGet
     */
    readonly limit?: any
}

/**
 * Request parameters for subcategoriesSlugGet operation in CategoriesApi.
 * @export
 * @interface CategoriesApiSubcategoriesSlugGetRequest
 */
export interface CategoriesApiSubcategoriesSlugGetRequest {
    /**
     * 
     * @type {any}
     * @memberof CategoriesApiSubcategoriesSlugGet
     */
    readonly slug: any
}

/**
 * CategoriesApi - object-oriented interface
 * @export
 * @class CategoriesApi
 * @extends {BaseAPI}
 */
export class CategoriesApi extends BaseAPI {
    /**
     * 
     * @summary List categories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public categoriesGet(options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).categoriesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get category
     * @param {CategoriesApiCategoriesSlugGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public categoriesSlugGet(requestParameters: CategoriesApiCategoriesSlugGetRequest, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).categoriesSlugGet(requestParameters.slug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Solutions under category
     * @param {CategoriesApiCategoriesSlugSolutionsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public categoriesSlugSolutionsGet(requestParameters: CategoriesApiCategoriesSlugSolutionsGetRequest, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).categoriesSlugSolutionsGet(requestParameters.slug, requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List subcategories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public subcategoriesGet(options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).subcategoriesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get subcategory
     * @param {CategoriesApiSubcategoriesSlugGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public subcategoriesSlugGet(requestParameters: CategoriesApiSubcategoriesSlugGetRequest, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).subcategoriesSlugGet(requestParameters.slug, options).then((request) => request(this.axios, this.basePath));
    }
}

