/* tslint:disable */
/* eslint-disable */
/**
 * Solutions API
 * REST API for technical solutions organized by categories and subcategories
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { MarkSolutionHelpful200Response } from '../models';
// @ts-ignore
import { PaginatedSolutions } from '../models';
// @ts-ignore
import { Solution } from '../models';
// @ts-ignore
import { SolutionInput } from '../models';
/**
 * SolutionsApi - axios parameter creator
 * @export
 */
export const SolutionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create solution
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSolution: async (solutionInput: SolutionInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'solutionInput' is not null or undefined
            assertParamExists('createSolution', 'solutionInput', solutionInput)
            const localVarPath = `/solutions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(solutionInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSolution: async (id: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteSolution', 'id', id)
            const localVarPath = `/solutions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutionById: async (id: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSolutionById', 'id', id)
            const localVarPath = `/solutions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search across title and content, optionally filter by subcategory
         * @summary List solutions
         * @param {any} [search] 
         * @param {any} [subcategory] Subcategory ID filter
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutions: async (search?: any, subcategory?: any, page?: any, limit?: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/solutions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (subcategory !== undefined) {
                localVarQueryParameter['subcategory'] = subcategory;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Solutions under subcategory
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutionsBySubcategory: async (slug: any, page?: any, limit?: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('getSolutionsBySubcategory', 'slug', slug)
            const localVarPath = `/subcategories/{slug}/solutions`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Mark solution helpful
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markSolutionHelpful: async (id: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('markSolutionHelpful', 'id', id)
            const localVarPath = `/solutions/{id}/helpful`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update solution
         * @param {any} id 
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSolution: async (id: any, solutionInput: SolutionInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateSolution', 'id', id)
            // verify required parameter 'solutionInput' is not null or undefined
            assertParamExists('updateSolution', 'solutionInput', solutionInput)
            const localVarPath = `/solutions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(solutionInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SolutionsApi - functional programming interface
 * @export
 */
export const SolutionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SolutionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create solution
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSolution(solutionInput: SolutionInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Solution>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSolution(solutionInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSolution(id: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSolution(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSolutionById(id: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Solution>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSolutionById(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Search across title and content, optionally filter by subcategory
         * @summary List solutions
         * @param {any} [search] 
         * @param {any} [subcategory] Subcategory ID filter
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSolutions(search?: any, subcategory?: any, page?: any, limit?: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedSolutions>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSolutions(search, subcategory, page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Solutions under subcategory
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSolutionsBySubcategory(slug: any, page?: any, limit?: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedSolutions>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSolutionsBySubcategory(slug, page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Mark solution helpful
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markSolutionHelpful(id: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MarkSolutionHelpful200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.markSolutionHelpful(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update solution
         * @param {any} id 
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSolution(id: any, solutionInput: SolutionInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Solution>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSolution(id, solutionInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SolutionsApi - factory interface
 * @export
 */
export const SolutionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SolutionsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create solution
         * @param {SolutionsApiCreateSolutionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSolution(requestParameters: SolutionsApiCreateSolutionRequest, options?: AxiosRequestConfig): AxiosPromise<Solution> {
            return localVarFp.createSolution(requestParameters.solutionInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete solution
         * @param {SolutionsApiDeleteSolutionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSolution(requestParameters: SolutionsApiDeleteSolutionRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSolution(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get solution
         * @param {SolutionsApiGetSolutionByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutionById(requestParameters: SolutionsApiGetSolutionByIdRequest, options?: AxiosRequestConfig): AxiosPromise<Solution> {
            return localVarFp.getSolutionById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Search across title and content, optionally filter by subcategory
         * @summary List solutions
         * @param {SolutionsApiGetSolutionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutions(requestParameters: SolutionsApiGetSolutionsRequest = {}, options?: AxiosRequestConfig): AxiosPromise<PaginatedSolutions> {
            return localVarFp.getSolutions(requestParameters.search, requestParameters.subcategory, requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Solutions under subcategory
         * @param {SolutionsApiGetSolutionsBySubcategoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSolutionsBySubcategory(requestParameters: SolutionsApiGetSolutionsBySubcategoryRequest, options?: AxiosRequestConfig): AxiosPromise<PaginatedSolutions> {
            return localVarFp.getSolutionsBySubcategory(requestParameters.slug, requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Mark solution helpful
         * @param {SolutionsApiMarkSolutionHelpfulRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markSolutionHelpful(requestParameters: SolutionsApiMarkSolutionHelpfulRequest, options?: AxiosRequestConfig): AxiosPromise<MarkSolutionHelpful200Response> {
            return localVarFp.markSolutionHelpful(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update solution
         * @param {SolutionsApiUpdateSolutionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSolution(requestParameters: SolutionsApiUpdateSolutionRequest, options?: AxiosRequestConfig): AxiosPromise<Solution> {
            return localVarFp.updateSolution(requestParameters.id, requestParameters.solutionInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createSolution operation in SolutionsApi.
 * @export
 * @interface SolutionsApiCreateSolutionRequest
 */
export interface SolutionsApiCreateSolutionRequest {
    /**
     * 
     * @type {SolutionInput}
     * @memberof SolutionsApiCreateSolution
     */
    readonly solutionInput: SolutionInput
}

/**
 * Request parameters for deleteSolution operation in SolutionsApi.
 * @export
 * @interface SolutionsApiDeleteSolutionRequest
 */
export interface SolutionsApiDeleteSolutionRequest {
    /**
     * 
     * @type {any}
     * @memberof SolutionsApiDeleteSolution
     */
    readonly id: any
}

/**
 * Request parameters for getSolutionById operation in SolutionsApi.
 * @export
 * @interface SolutionsApiGetSolutionByIdRequest
 */
export interface SolutionsApiGetSolutionByIdRequest {
    /**
     * 
     * @type {any}
     * @memberof SolutionsApiGetSolutionById
     */
    readonly id: any
}

/**
 * Request parameters for getSolutions operation in SolutionsApi.
 * @export
 * @interface SolutionsApiGetSolutionsRequest
 */
export interface SolutionsApiGetSolutionsRequest {
    /**
     * 
     * @type {any}
     * @memberof SolutionsApiGetSolutions
     */
    readonly search?: any

    /**
     * Subcategory ID filter
     * @type {any}
     * @memberof SolutionsApiGetSolutions
     */
    readonly subcategory?: any

    /**
     * 
     * @type {any}
     * @memberof SolutionsApiGetSolutions
     */
    readonly page?: any

    /**
     * 
     * @type {any}
     * @memberof SolutionsApiGetSolutions
     */
    readonly limit?: any
}

/**
 * Request parameters for getSolutionsBySubcategory operation in SolutionsApi.
 * @export
 * @interface SolutionsApiGetSolutionsBySubcategoryRequest
 */
export interface SolutionsApiGetSolutionsBySubcategoryRequest {
    /**
     * 
     * @type {any}
     * @memberof SolutionsApiGetSolutionsBySubcategory
     */
    readonly slug: any

    /**
     * 
     * @type {any}
     * @memberof SolutionsApiGetSolutionsBySubcategory
     */
    readonly page?: any

    /**
     * 
     * @type {any}
     * @memberof SolutionsApiGetSolutionsBySubcategory
     */
    readonly limit?: any
}

/**
 * Request parameters for markSolutionHelpful operation in SolutionsApi.
 * @export
 * @interface SolutionsApiMarkSolutionHelpfulRequest
 */
export interface SolutionsApiMarkSolutionHelpfulRequest {
    /**
     * 
     * @type {any}
     * @memberof SolutionsApiMarkSolutionHelpful
     */
    readonly id: any
}

/**
 * Request parameters for updateSolution operation in SolutionsApi.
 * @export
 * @interface SolutionsApiUpdateSolutionRequest
 */
export interface SolutionsApiUpdateSolutionRequest {
    /**
     * 
     * @type {any}
     * @memberof SolutionsApiUpdateSolution
     */
    readonly id: any

    /**
     * 
     * @type {SolutionInput}
     * @memberof SolutionsApiUpdateSolution
     */
    readonly solutionInput: SolutionInput
}

/**
 * SolutionsApi - object-oriented interface
 * @export
 * @class SolutionsApi
 * @extends {BaseAPI}
 */
export class SolutionsApi extends BaseAPI {
    /**
     * 
     * @summary Create solution
     * @param {SolutionsApiCreateSolutionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public createSolution(requestParameters: SolutionsApiCreateSolutionRequest, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).createSolution(requestParameters.solutionInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete solution
     * @param {SolutionsApiDeleteSolutionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public deleteSolution(requestParameters: SolutionsApiDeleteSolutionRequest, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).deleteSolution(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get solution
     * @param {SolutionsApiGetSolutionByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public getSolutionById(requestParameters: SolutionsApiGetSolutionByIdRequest, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).getSolutionById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Search across title and content, optionally filter by subcategory
     * @summary List solutions
     * @param {SolutionsApiGetSolutionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public getSolutions(requestParameters: SolutionsApiGetSolutionsRequest = {}, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).getSolutions(requestParameters.search, requestParameters.subcategory, requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Solutions under subcategory
     * @param {SolutionsApiGetSolutionsBySubcategoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public getSolutionsBySubcategory(requestParameters: SolutionsApiGetSolutionsBySubcategoryRequest, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).getSolutionsBySubcategory(requestParameters.slug, requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Mark solution helpful
     * @param {SolutionsApiMarkSolutionHelpfulRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public markSolutionHelpful(requestParameters: SolutionsApiMarkSolutionHelpfulRequest, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).markSolutionHelpful(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update solution
     * @param {SolutionsApiUpdateSolutionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public updateSolution(requestParameters: SolutionsApiUpdateSolutionRequest, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).updateSolution(requestParameters.id, requestParameters.solutionInput, options).then((request) => request(this.axios, this.basePath));
    }
}

