/* tslint:disable */
/* eslint-disable */
/**
 * Solutions API
 * REST API for technical solutions organized by categories and subcategories
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PaginatedSolutions } from '../models';
// @ts-ignore
import { Solution } from '../models';
// @ts-ignore
import { SolutionInput } from '../models';
// @ts-ignore
import { SolutionsIdHelpfulPost200Response } from '../models';
/**
 * SolutionsApi - axios parameter creator
 * @export
 */
export const SolutionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Search across title and content, optionally filter by subcategory
         * @summary List solutions
         * @param {any} [search] 
         * @param {any} [subcategory] Subcategory ID filter
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solutionsGet: async (search?: any, subcategory?: any, page?: any, limit?: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/solutions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (subcategory !== undefined) {
                localVarQueryParameter['subcategory'] = subcategory;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solutionsIdDelete: async (id: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('solutionsIdDelete', 'id', id)
            const localVarPath = `/solutions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solutionsIdGet: async (id: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('solutionsIdGet', 'id', id)
            const localVarPath = `/solutions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Mark solution helpful
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solutionsIdHelpfulPost: async (id: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('solutionsIdHelpfulPost', 'id', id)
            const localVarPath = `/solutions/{id}/helpful`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update solution
         * @param {any} id 
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solutionsIdPut: async (id: any, solutionInput: SolutionInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('solutionsIdPut', 'id', id)
            // verify required parameter 'solutionInput' is not null or undefined
            assertParamExists('solutionsIdPut', 'solutionInput', solutionInput)
            const localVarPath = `/solutions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(solutionInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create solution
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solutionsPost: async (solutionInput: SolutionInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'solutionInput' is not null or undefined
            assertParamExists('solutionsPost', 'solutionInput', solutionInput)
            const localVarPath = `/solutions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(solutionInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Solutions under subcategory
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subcategoriesSlugSolutionsGet: async (slug: any, page?: any, limit?: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('subcategoriesSlugSolutionsGet', 'slug', slug)
            const localVarPath = `/subcategories/{slug}/solutions`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SolutionsApi - functional programming interface
 * @export
 */
export const SolutionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SolutionsApiAxiosParamCreator(configuration)
    return {
        /**
         * Search across title and content, optionally filter by subcategory
         * @summary List solutions
         * @param {any} [search] 
         * @param {any} [subcategory] Subcategory ID filter
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async solutionsGet(search?: any, subcategory?: any, page?: any, limit?: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedSolutions>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.solutionsGet(search, subcategory, page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async solutionsIdDelete(id: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.solutionsIdDelete(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get solution
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async solutionsIdGet(id: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Solution>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.solutionsIdGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Mark solution helpful
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async solutionsIdHelpfulPost(id: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SolutionsIdHelpfulPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.solutionsIdHelpfulPost(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update solution
         * @param {any} id 
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async solutionsIdPut(id: any, solutionInput: SolutionInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Solution>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.solutionsIdPut(id, solutionInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Create solution
         * @param {SolutionInput} solutionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async solutionsPost(solutionInput: SolutionInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Solution>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.solutionsPost(solutionInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Solutions under subcategory
         * @param {any} slug 
         * @param {any} [page] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async subcategoriesSlugSolutionsGet(slug: any, page?: any, limit?: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedSolutions>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subcategoriesSlugSolutionsGet(slug, page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SolutionsApi - factory interface
 * @export
 */
export const SolutionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SolutionsApiFp(configuration)
    return {
        /**
         * Search across title and content, optionally filter by subcategory
         * @summary List solutions
         * @param {SolutionsApiSolutionsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solutionsGet(requestParameters: SolutionsApiSolutionsGetRequest = {}, options?: AxiosRequestConfig): AxiosPromise<PaginatedSolutions> {
            return localVarFp.solutionsGet(requestParameters.search, requestParameters.subcategory, requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete solution
         * @param {SolutionsApiSolutionsIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solutionsIdDelete(requestParameters: SolutionsApiSolutionsIdDeleteRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.solutionsIdDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get solution
         * @param {SolutionsApiSolutionsIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solutionsIdGet(requestParameters: SolutionsApiSolutionsIdGetRequest, options?: AxiosRequestConfig): AxiosPromise<Solution> {
            return localVarFp.solutionsIdGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Mark solution helpful
         * @param {SolutionsApiSolutionsIdHelpfulPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solutionsIdHelpfulPost(requestParameters: SolutionsApiSolutionsIdHelpfulPostRequest, options?: AxiosRequestConfig): AxiosPromise<SolutionsIdHelpfulPost200Response> {
            return localVarFp.solutionsIdHelpfulPost(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update solution
         * @param {SolutionsApiSolutionsIdPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solutionsIdPut(requestParameters: SolutionsApiSolutionsIdPutRequest, options?: AxiosRequestConfig): AxiosPromise<Solution> {
            return localVarFp.solutionsIdPut(requestParameters.id, requestParameters.solutionInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create solution
         * @param {SolutionsApiSolutionsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solutionsPost(requestParameters: SolutionsApiSolutionsPostRequest, options?: AxiosRequestConfig): AxiosPromise<Solution> {
            return localVarFp.solutionsPost(requestParameters.solutionInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Solutions under subcategory
         * @param {SolutionsApiSubcategoriesSlugSolutionsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subcategoriesSlugSolutionsGet(requestParameters: SolutionsApiSubcategoriesSlugSolutionsGetRequest, options?: AxiosRequestConfig): AxiosPromise<PaginatedSolutions> {
            return localVarFp.subcategoriesSlugSolutionsGet(requestParameters.slug, requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for solutionsGet operation in SolutionsApi.
 * @export
 * @interface SolutionsApiSolutionsGetRequest
 */
export interface SolutionsApiSolutionsGetRequest {
    /**
     * 
     * @type {any}
     * @memberof SolutionsApiSolutionsGet
     */
    readonly search?: any

    /**
     * Subcategory ID filter
     * @type {any}
     * @memberof SolutionsApiSolutionsGet
     */
    readonly subcategory?: any

    /**
     * 
     * @type {any}
     * @memberof SolutionsApiSolutionsGet
     */
    readonly page?: any

    /**
     * 
     * @type {any}
     * @memberof SolutionsApiSolutionsGet
     */
    readonly limit?: any
}

/**
 * Request parameters for solutionsIdDelete operation in SolutionsApi.
 * @export
 * @interface SolutionsApiSolutionsIdDeleteRequest
 */
export interface SolutionsApiSolutionsIdDeleteRequest {
    /**
     * 
     * @type {any}
     * @memberof SolutionsApiSolutionsIdDelete
     */
    readonly id: any
}

/**
 * Request parameters for solutionsIdGet operation in SolutionsApi.
 * @export
 * @interface SolutionsApiSolutionsIdGetRequest
 */
export interface SolutionsApiSolutionsIdGetRequest {
    /**
     * 
     * @type {any}
     * @memberof SolutionsApiSolutionsIdGet
     */
    readonly id: any
}

/**
 * Request parameters for solutionsIdHelpfulPost operation in SolutionsApi.
 * @export
 * @interface SolutionsApiSolutionsIdHelpfulPostRequest
 */
export interface SolutionsApiSolutionsIdHelpfulPostRequest {
    /**
     * 
     * @type {any}
     * @memberof SolutionsApiSolutionsIdHelpfulPost
     */
    readonly id: any
}

/**
 * Request parameters for solutionsIdPut operation in SolutionsApi.
 * @export
 * @interface SolutionsApiSolutionsIdPutRequest
 */
export interface SolutionsApiSolutionsIdPutRequest {
    /**
     * 
     * @type {any}
     * @memberof SolutionsApiSolutionsIdPut
     */
    readonly id: any

    /**
     * 
     * @type {SolutionInput}
     * @memberof SolutionsApiSolutionsIdPut
     */
    readonly solutionInput: SolutionInput
}

/**
 * Request parameters for solutionsPost operation in SolutionsApi.
 * @export
 * @interface SolutionsApiSolutionsPostRequest
 */
export interface SolutionsApiSolutionsPostRequest {
    /**
     * 
     * @type {SolutionInput}
     * @memberof SolutionsApiSolutionsPost
     */
    readonly solutionInput: SolutionInput
}

/**
 * Request parameters for subcategoriesSlugSolutionsGet operation in SolutionsApi.
 * @export
 * @interface SolutionsApiSubcategoriesSlugSolutionsGetRequest
 */
export interface SolutionsApiSubcategoriesSlugSolutionsGetRequest {
    /**
     * 
     * @type {any}
     * @memberof SolutionsApiSubcategoriesSlugSolutionsGet
     */
    readonly slug: any

    /**
     * 
     * @type {any}
     * @memberof SolutionsApiSubcategoriesSlugSolutionsGet
     */
    readonly page?: any

    /**
     * 
     * @type {any}
     * @memberof SolutionsApiSubcategoriesSlugSolutionsGet
     */
    readonly limit?: any
}

/**
 * SolutionsApi - object-oriented interface
 * @export
 * @class SolutionsApi
 * @extends {BaseAPI}
 */
export class SolutionsApi extends BaseAPI {
    /**
     * Search across title and content, optionally filter by subcategory
     * @summary List solutions
     * @param {SolutionsApiSolutionsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public solutionsGet(requestParameters: SolutionsApiSolutionsGetRequest = {}, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).solutionsGet(requestParameters.search, requestParameters.subcategory, requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete solution
     * @param {SolutionsApiSolutionsIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public solutionsIdDelete(requestParameters: SolutionsApiSolutionsIdDeleteRequest, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).solutionsIdDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get solution
     * @param {SolutionsApiSolutionsIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public solutionsIdGet(requestParameters: SolutionsApiSolutionsIdGetRequest, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).solutionsIdGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Mark solution helpful
     * @param {SolutionsApiSolutionsIdHelpfulPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public solutionsIdHelpfulPost(requestParameters: SolutionsApiSolutionsIdHelpfulPostRequest, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).solutionsIdHelpfulPost(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update solution
     * @param {SolutionsApiSolutionsIdPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public solutionsIdPut(requestParameters: SolutionsApiSolutionsIdPutRequest, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).solutionsIdPut(requestParameters.id, requestParameters.solutionInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create solution
     * @param {SolutionsApiSolutionsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public solutionsPost(requestParameters: SolutionsApiSolutionsPostRequest, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).solutionsPost(requestParameters.solutionInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Solutions under subcategory
     * @param {SolutionsApiSubcategoriesSlugSolutionsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolutionsApi
     */
    public subcategoriesSlugSolutionsGet(requestParameters: SolutionsApiSubcategoriesSlugSolutionsGetRequest, options?: AxiosRequestConfig) {
        return SolutionsApiFp(this.configuration).subcategoriesSlugSolutionsGet(requestParameters.slug, requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }
}

